#### Working space to use as a stand in for a main file

In [1]:
#Our Modules
import modules.wec_dyn as wec_dyn
import modules.time_avg_power 
import Econ
import capy.notfinalbutworks as nf
import capy.geometry
import capy.hydrodyno
import capy.hydrostatics
#import capy1
#Other packages:
import numpy as np


In [2]:
# Variables and Parameters:
K_p = 100 #N/m : Proportional gain
K_I = 10 #N/m.s : Integral Gain
L = 100 #m : WEC spacing
d = 0.36 #m : WEC diameter
S= 0 # Spectral density function or array?
k = 1000 # N/m : spring constant
s = 10 #MPa : Nominal stiffness
b = 10 #N.s/m : nominal damping

# Constraints
P_min = 10000 #W : minimum power Watts
LCOE_max = 200 #$/MWhr

# Define design vector
x=[L,d,k,s]
# Define parameters
p=[]
# Should some of these be internal variables determined during optimization? 
#...ex: control tuning parameters


In [4]:
nf.run(2,20)

Deprecation warning: The class Sphere() is deprecated. Please prefer the function capytaine.meshes.predefined.mesh_sphere()
Deprecation warning: The class Sphere() is deprecated. Please prefer the function capytaine.meshes.predefined.mesh_sphere()


<xarray.DataArray (omega: 1, radiating_dof: 6)>
array([[ 2.09525821e-03+4.65580755e-01j,  6.55697043e-17+5.62623406e-17j,
         9.81547565e-01-1.23729062e-03j,  2.35355137e-16+2.13842772e-17j,
         2.54666164e-03+5.66880122e-01j, -3.22425054e-15+9.07118772e-17j]])
Coordinates:
  * omega          (omega) float64 1.0
  * radiating_dof  (radiating_dof) object 'Surge' 'Sway' ... 'Pitch' 'Yaw'


(<xarray.DataArray (omega: 1, radiating_dof: 6)>
 array([[ 2.09525821e-03+4.65580755e-01j,  6.55697043e-17+5.62623406e-17j,
          9.81547565e-01-1.23729062e-03j,  2.35355137e-16+2.13842772e-17j,
          2.54666164e-03+5.66880122e-01j, -3.22425054e-15+9.07118772e-17j]])
 Coordinates:
   * omega          (omega) float64 1.0
   * radiating_dof  (radiating_dof) object 'Surge' 'Sway' ... 'Pitch' 'Yaw',
 <xarray.DataArray (omega: 1, radiating_dof: 6)>
 array([[ 2.05404453e-03+5.24700880e-01j,  2.24344441e-02+5.75604135e-05j,
          2.91933162e-01-1.80708197e-03j,  2.94797777e-02-1.84421667e-04j,
          7.92071629e-04+2.01259905e-01j, -1.08849781e-04-2.79426454e-02j]])
 Coordinates:
   * omega          (omega) float64 1.0
   * radiating_dof  (radiating_dof) object 'Surge' 'Sway' ... 'Pitch' 'Yaw')

In [25]:
# Build DoE input vectors
x1=[0,0,0,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1,1,-1]
x2=[0,1,-1,0,0,-1,1,-1,1,1,-1,-1,1,1,-1,1,-1]
x3=[0,1,-1,1,1,0,0,-1,1,-1,1,1,-1,-1,1,1,-1]
x4=[0,1,-1,1,1,1,-1,0,0,-1,1,-1,1,1,-1,-1,1]
x=np.zeros([17,4])
r_doe=[2,3,4]
L_doe=[200,300,400]
k_doe=[100,200,300]
s_doe=[10,20,30]

for i in range(np.size(x1)):
    x[i]=[r_doe[x1[i]+1],L_doe[x2[i]+1],k_doe[x3[i]+1],s_doe[x4[i]+1]]
    
    #print(x[i])

17

In [4]:
def evaluate(x,p):
    out1 = wec_dyn(x,p)
    out2 = capy(x,p,out1)
    out3 = time_avg_power(x,p,out2)
    out4 = econ(x,p,out3)
    y = out4
    # Define order of modules. connect inputs and outputs
    
    return y

test


In [ ]:
# Build optimization framework down here. 


